version: "3.9"

networks:
  food:
    
services:
  app:
    container_name: food-api
    build: .
    restart: always
    ports: 
      - "3001:3001"
    volumes:
      - .:/code
    networks:
      - food
    depends_on:
    - mongo
  mongo:
    container_name: food-mongo-srv
    image: mongo
    networks:
      - food
    ports:
      - 27017:27017